
CREATE TABLE  IF NOT EXISTS person(
    id INTEGER PRIMARY  KEY AUTOINCREMENT,
    name TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS chore (
    id INTEGER PRIMARY  KEY AUTOINCREMENT,
    description TEXT UNIQUE NOT NULL,
    level INTEGER NOT NULL,
    frequency INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS assignment(
  id INTEGER PRIMARY  KEY AUTOINCREMENT,
  person_id INTEGER NOT NULL REFERENCES person(id) ON DELETE CASCADE,
  chore_id INTEGER NOT NULL REFERENCES chore(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS task(
  id INTEGER PRIMARY  KEY AUTOINCREMENT,
  person_id INTEGER NOT NULL REFERENCES person(id) ON DELETE CASCADE,
  chore_id INTEGER NOT NULL REFERENCES chore(id) ON DELETE CASCADE,
  done DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

